name: Papa Bot
on: workflow_dispatch
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pywikibot requests
      - name: Run Papa bot
        env:
          WIKI_USERNAME: Gayle-Bot
          WIKI_PASSWORD: PapaBot@o11j8tnp1b6saj612jnjm5sl0giehjsp
        run: python papa_bot.py
